### ISSUE TITLE
Email formular virker ikke

### ISSUE THREAD

**Issue by benjaoming** [djangocph/djangocph.dk#1]
Server fejl 500

Men virkelig nice arbejde!! Lækkert at have noget info derude.

Hvem skal læse mails? Skal vi lave en lille intern mailingliste, som bare forwarder? Jeg kan godt lave en djangocph@overtag.dk og forwarde til rette vedkommende....?

**Comment by valberg** [comment]
Oh! That was unfortunate!
Right now only @emilkjer has access to the server, so maybe he can look at the logs :)
@benjaoming we already have such a mailinglist - team@djangocph.dk :)

btw. please write in English in the future ;)

**Comment by benjaoming** [comment]
Oh cool!! Sry about the Danish, I guess I just miss it.

**Comment by valberg** [comment]
It has been fixed :)

**Comment by benjaoming** [comment]
Hurray for the fixing!!!
